apiVersion: crossplane.dfds.cloud/v1alpha1
kind: SqlDatabaseInstance
metadata:
  namespace: default
  name: dynamic-claim-example
spec:
  parameters:
    region: eu-west-1
    instanceSize: small
    instanceClass: burstable
    administratorUsername: masteruser
    storageSize: 30
    databaseEngine: postgres
    databaseEngineVersion: "13"
    skipFinalSnapshotBeforeDeletion: true
  compositionSelector:
    matchLabels:
      purpose: database
      provider: aws
  
  writeConnectionSecretToRef:
    name: dynamic-claim-example-secret