apiVersion: crossplane.dfds.cloud/v1alpha1
kind: CompositeDatabaseInstance
metadata:
  # Composite resources are cluster scoped, so there's no need for a namespace.
  name: example-dfds-rds
spec:
  parameters:
    region: eu-west-1
    dbInstanceClass: db.t2.small
    masterUsername: masteruser
    allocatedStorage: 20
    engine: postgres
    engineVersion: "9.6"
    skipFinalSnapshotBeforeDeletion: true
  compositionRef:
    name: compositedatabaseinstances.crossplane.dfds.cloud
  writeConnectionSecretToRef:
    namespace: default
    name: example-databaseinstance