apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default-aws
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: default
      name: aws-creds
      key: creds