apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrbacs.crossplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xrbacs.crossplane.dfds.cloud
  group: crossplane.dfds.cloud
  names:
    kind: XRBAC
    plural: xrbacs
  versions: 
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:          
              apiGroup:
                type: array
                items:
                  type: string
              resourceType:
                type: array
                items:
                  type: string                    
              resourceName:
                type: string            
              resourceNamespace:
                type: string
            required:
            - apiGroup
            - resourceType
            - resourceName
            - resourceNamespace
          status:
            type: object
            properties:
              createdResources:
                description: list of resources created in this composition
                type: object
                properties:
                  clusterrole: 
                    description: Name of the provisioned clusterrole
                    type: string
                  clusterrolebinding:
                    description: Name of the provisioned clusterrolebinding
                    type: string