apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xrbacv1s.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xrbacv1s.xplane.dfds.cloud
  group: xplane.dfds.cloud
  names:
    kind: XRBACV1
    plural: xrbacv1s
  versions: 
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:          
              apiGroups:
                type: array
                items:
                  type: string
              resourceTypes:
                type: array
                items:
                  type: string                    
              resourceName:
                type: string            
              resourceNamespace:
                type: string
              providerConfigRef:
                type: object
                description: "A reference to the ProviderConfig of the cluster that services should be deployed to."
                properties:
                  name:
                    type: string
                    description: "Name of the Kubernetes provider configuration."
                required:
                - name
            required:
            - apiGroups
            - resourceTypes
            - resourceName
            - resourceNamespace
            - providerConfigRef
          status:
            type: object
            properties:
              createdResources:
                description: list of resources created in this composition
                type: object
                properties:
                  clusterrole: 
                    description: Name of the provisioned clusterrole
                    type: string
                  clusterrolebinding:
                    description: Name of the provisioned clusterrolebinding
                    type: string