apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsbucketsv2.storage.crossplane.myorg
spec:
  defaultCompositionRef:
    name: xawsbucketsv2.storage.crossplane.myorg
  group: storage.crossplane.myorg
  names:
    kind: XAWSBucketv2
    plural: xawsbucketsv2
  claimNames:
    kind: AWSBucketv2
    plural: awsbucketsv2
  versions:
  - name: v1alpha2
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:     
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    description: Geographic location of this Database server.
                    type: string
                    enum: ["ireland", "germany"]               
                  acl:
                    type: string
                  deletionPolicy: 
                    description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                    type: string
                    default: "Delete"