apiVersion: xplane.dfds.cloud/v1alpha1
kind: SqlDatabaseInstance
metadata:
  namespace: my-namespace
  name: dynamic-claim-sql-nonprod-example
spec:
  parameters:
    isProduction: false
  compositionSelector:
    matchLabels:
      provider: aws
