apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawscertificateauthorities.certs.crossplane.dfds.cloud
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: certs.crossplane.dfds.cloud/v1alpha1
    kind: XAWSCertificateAuthority

  patchSets:
  - name: configname
    patches:
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-aws"
      policy:
        fromFieldPath: Required
  resources:
  - name: certificateauthority
    base:
      apiVersion: acmpca.aws.crossplane.io/v1beta1
      kind: CertificateAuthority
      spec:
        forProvider:
          region: eu-west-1
    patches:
    - type: PatchSet
      patchSetName: configname
    - fromFieldPath: spec.parameters
      toFieldPath: spec.forProvider
    - type: ToCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "status.createdResources.certificateauthority"
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
    - fromFieldPath: spec.parameters.deletionPolicy
      toFieldPath: spec.deletionPolicy    
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions
      toFieldPath: status.instanceConditions
      policy:
        fromFieldPath: Optional

  - name: rbac
    base:
      apiVersion: crossplane.dfds.cloud/v1alpha1
      kind: XRBAC
      spec:
        resourceTypes:
        - certificateauthorities
        apiGroups:
        - acmpca.aws.crossplane.io
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.resourceName
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.resourceNamespace
    - type: ToCompositeFieldPath
      fromFieldPath: status.createdResources
      toFieldPath: status.createdResources.rbac
      policy:
        fromFieldPath: Optional