apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xconfluentserviceaccountv1s.messaging.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xconfluentserviceaccountv1s.messaging.xplane.dfds.cloud
  group: messaging.xplane.dfds.cloud
  names:
    kind: XConfluentServiceAccountV1
    plural: xconfluentserviceaccountv1s
  claimNames:
    kind: ConfluentServiceAccountV1
    plural: confluentserviceaccountv1s
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                serviceaccountid:
                  type: string
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    deletionPolicy:
                      description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                      type: string
                      default: "Orphan"
                      enum:
                      - Delete
                      - Orphan
                    environment:
                      description: Specify the target environment
                      type: string
                      enum: ["prod", "dev"]
