apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: compositesqldatabaseinstances.crossplane.dfds.cloud
  labels:
    purpose: database
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: crossplane.dfds.cloud/v1alpha1
    kind: CompositeSqlDatabaseInstance
  patchSets:
  - name: object-metadata
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.metadata.name    
      policy:
        fromFieldPath: Required       
    - fromFieldPath: metadata.labels
      toFieldPath: spec.forProvider.manifest.metadata.labels
      policy:
        fromFieldPath: Required
  - name: configname
    patches:
    - fromFieldPath: spec.claimRef.namespace    
      toFieldPath: spec.providerConfigRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-aws"      
      policy:
        fromFieldPath: Required        
  resources:
  - name: role
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRole
            metadata:
              name: deployed-using-crossplane
              labels:
                managed-by: "crossplane"
            rules:
            - apiGroups: ["ec2.aws.crossplane.io"]
              resources: ["securitygroups"]
              resourceNames: [ ]
              verbs: ["get"]
            - apiGroups: ["database.aws.crossplane.io"]
              resources: ["rdsinstances"]
              resourceNames: [ ]
              verbs: ["get"]              
        providerConfigRef:
          name: kubernetes-provider        
    patches:
    - type: PatchSet
      patchSetName: object-metadata
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.rules[0].resourceNames[0]
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.rules[1].resourceNames[0]

  - name: rolebinding
    base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: ClusterRoleBinding
            metadata:
              name: myrb
            roleRef:
              apiGroup: rbac.authorization.k8s.io
              kind: ClusterRole
              name: roleref
            subjects:
            - apiGroup: rbac.authorization.k8s.io
              kind: Group
              name: mynamespace
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - type: PatchSet
      patchSetName: object-metadata    
    - fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.manifest.roleRef.name
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.manifest.subjects[0].name
  - name: securitygroup
    base:
      apiVersion: ec2.aws.crossplane.io/v1beta1
      kind: SecurityGroup
      spec:
        forProvider:
          region: eu-west-1
          description: Allow access to PostgreSQL
          ingress:
            - fromPort: 5432
              toPort: 5432
              ipProtocol: tcp
              ipRanges:
                - cidrIp: 0.0.0.0/0
                  description: postgresql
    patches:
    - type: PatchSet
      patchSetName: configname    
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
    - fromFieldPath: metadata.name
      toFieldPath: "spec.forProvider.groupName"
    - type: ToCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "status.securitygroup"      
  - name: rdinstance
    base:
      apiVersion: database.aws.crossplane.io/v1beta1
      kind: RDSInstance
      spec:
        forProvider:
          dbInstanceClass: db.t3.small
          engine: postgres
          masterUsername: masteruser
          skipFinalSnapshotBeforeDeletion: true
          vpcSecurityGroupIDSelector:
            matchControllerRef: true
        writeConnectionSecretToRef:
          namespace: crossplane-system
    patches:
    - type: PatchSet
      patchSetName: configname    
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name    
    - fromFieldPath: "metadata.uid"
      toFieldPath: "spec.writeConnectionSecretToRef.name"
      transforms:
      - type: string
        string:
          fmt: "%s-databaseserver"
    - fromFieldPath: "spec.parameters.databaseEngine"
      toFieldPath: "spec.forProvider.engine"
    - fromFieldPath: "spec.parameters.databaseEngineVersion"
      toFieldPath: "spec.forProvider.engineVersion"
    - fromFieldPath: "spec.parameters.region"
      toFieldPath: "spec.forProvider.region"
      transforms:
      - type: map
        map:
          eu-west-1: eu-west-1
    - fromFieldPath: "spec.parameters.storageSize"
      toFieldPath: "spec.forProvider.allocatedStorage"
    - fromFieldPath: "spec.parameters.administratorUsername"
      toFieldPath: "spec.forProvider.masterUsername"
    - type: CombineFromComposite
      combine:
        variables: 
          - fromFieldPath: spec.parameters.instanceClass          
          - fromFieldPath: spec.parameters.instanceSize 
        strategy: string        
        string:
          fmt: "%s-%s"
      toFieldPath: spec.forProvider.dbInstanceClass
      transforms:
      - type: map
        map:
          burstable-small: db.t3.small
          burstable-medium: db.t3.medium
          burstable-large: db.t3.large
    - type: ToCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "status.rdsinstance"      
    connectionDetails:
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    - name: hostname
      fromConnectionSecretKey: endpoint
    - type: FromValue
      name: port
      value: "5432"
    readinessChecks:
    - type: MatchString
      fieldPath: "status.atProvider.dbInstanceStatus"
      matchString: "available"
  writeConnectionSecretsToNamespace: crossplane-system