apiVersion: dns.xplane.dfds.cloud/v1alpha1
kind: AWSResourceRecordSetV1alpha1
metadata:
  name: awsresoucerecordsetdfds.example.dfds.cloud
  namespace: my-namespace
spec:
  parameters:
    type: CNAME
    ttl: 300
    resourceRecords:
    - value: "www.samditest.dfds.cloud"
    zoneIdSelector:
      matchLabels: # examples of labels that can be used. Note: This depends on how the hostedzone object was created!
        crossplane.io/claim-name: awshostedzonedfds2
        crossplane.io/claim-namespace: my-namespace
