apiVersion: cdn.xplane.dfds.cloud/v1alpha1
kind: AWSDistributionV1
metadata:
  name: awsdistributiondfds4
  namespace: my-namespace
spec:
  parameters:
    region: us-east-1
    distributionConfig:
      enabled: true
      comment: Example CloudFront Distribution 3
      priceClass: PriceClass_100
      origins:
        items:
          - domainName: api.dfds.com
            id: customOrigin1
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "https-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - SSLv3
                quantity: 1
          - domainName: app.hellman.oxygen.dfds.cloud
            id: customOrigin2
            customOriginConfig:
              httpPort: 80
              originProtocolPolicy: "https-only"
              originReadTimeout: 10
              originKeepaliveTimeout: 5
              httpSPort: 443
              originSSLProtocols:
                items:
                  - TLSv1.2
                quantity: 1                
      cacheBehaviors:
        quantity: 3
        items:
        - pathPattern: /server/*/consent
          smoothStreaming: false
          targetOriginID: customOrigin1
          compress: true
          viewerProtocolPolicy: redirect-to-https
          allowedMethods:        
            cachedMethods:
              items:
              - HEAD
              - GET
              quantity: 2
            items:
            - GET 
            - HEAD 
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
            quantity: 7
          forwardedValues:
            queryString: true 
            queryStringCacheKeys:
              quantity: 0
            cookies:
              forward: all
            headers:
              items:
              - Accept
              - Accept-Charset
              - Accept-Encoding
              - Accept-Language
              - Authorization
              - Accept-Datetime
              - Referer
              - Origin
              quantity: 8  
          lambdaFunctionAssociations:
            quantity: 0
          minTTL: 0
          maxTTL: 0
          defaultTTL: 0
          fieldLevelEncryptionID: ""
        - pathPattern: /server/*/consent/*
          smoothStreaming: false
          targetOriginID: customOrigin1
          compress: true
          viewerProtocolPolicy: redirect-to-https
          allowedMethods:        
            cachedMethods:
              items:
              - HEAD
              - GET
              quantity: 2
            items:
            - GET 
            - HEAD 
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
            quantity: 7
          forwardedValues:
            queryString: true 
            queryStringCacheKeys:
              quantity: 0
            cookies:
              forward: all
            headers:
              items:
              - Accept
              - Accept-Charset
              - Accept-Encoding
              - Accept-Language
              - Authorization
              - Accept-Datetime
              - Referer
              - Origin
              quantity: 8  
          lambdaFunctionAssociations:
            quantity: 0
          minTTL: 0
          maxTTL: 0
          defaultTTL: 0
          fieldLevelEncryptionID: ""          
        - pathPattern: /*/services-email-validation-api/*
          smoothStreaming: false # Why is it required??
          targetOriginID: customOrigin2
          compress: false
          viewerProtocolPolicy: https-only
          allowedMethods:        
            cachedMethods: # Why is it required??
              items:
              - HEAD
              - GET
              quantity: 2
            items:
            - GET 
            - HEAD 
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
            quantity: 7
          forwardedValues:
            queryString: true 
            queryStringCacheKeys:  # Why is this required ?
              quantity: 0          # Why is this required ?              
            cookies:
              forward: all
            headers:
              items:
              - Accept
              - Accept-Charset
              - Accept-Encoding
              - Accept-Language
              - Authorization
              - Accept-Datetime
              - Referer
              - Origin
              quantity: 8  
          lambdaFunctionAssociations:
            quantity: 0
          minTTL: 0
          maxTTL: 0
          defaultTTL: 0
          fieldLevelEncryptionID: ""
      defaultCacheBehavior:
        targetOriginID: customOrigin2
        compress: false
        viewerProtocolPolicy: https-only
        allowedMethods:
          cachedMethods: # is not required before adding cacheBehaviors section!
            items:
            - HEAD
            - GET        
            quantity: 2            
          items:
          - GET 
          - HEAD 
          - OPTIONS
          - PUT
          - POST
          - PATCH
          - DELETE
          quantity: 7
        minTTL: 0
        maxTTL: 0
        defaultTTL: 0
        forwardedValues:
          queryString: true
          cookies:
            forward: all
          headers:
            items:
            - Accept
            - Accept-Charset
            - Accept-Encoding
            - Accept-Language
            - Authorization
            - Accept-Datetime
            - Referer
            - Origin
            quantity: 8
        lambdaFunctionAssociations: # is not required before adding cacheBehaviors section!
          quantity: 0