apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsiamrolepolicyattachments.identity.crossplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xawsiamrolepolicyattachments.identity.crossplane.dfds.cloud
  group: identity.crossplane.dfds.cloud
  names:
    kind: XAWSIAMRolePolicyAttachment
    plural: xawsiamrolepolicyattachments
  claimNames:
    kind: AWSIAMRolePolicyAttachment
    plural: awsiamrolepolicyattachments
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              createdResources:
                description: list of resources created for this claim
                type: object
                properties:
                  iamrolepolicyattachement:
                    description: Name of the provisioned IAM role
                    type: string
                  rbac:
                    description: list of the provisioned RBAC resources
                    type: object
                    x-kubernetes-preserve-unknown-fields: true                   
          spec:
            description: An RolePolicyAttachmentSpec defines the desired state of
              an RolePolicyAttachment.          
            type: object
            properties:
              parameters:
                type: object
                properties:
                  deletionPolicy: 
                    default: Delete
                    description: DeletionPolicy specifies what will happen to the underlying
                      external when this managed resource is deleted - either "Delete"
                      or "Orphan" the external resource.
                    enum:
                    - Orphan
                    - Delete
                    type: string
                  policyArn:
                    description: PolicyARN is the Amazon Resource Name (ARN) of the
                      IAM policy you want to attach.
                    type: string
                  policyArnRef:
                    description: PolicyARNRef references an Policy to retrieve its
                      Policy ARN.
                    properties:
                      name:
                        description: Name of the referenced object.
                        type: string
                    required:
                    - name
                    type: object
                  policyArnSelector:
                    description: PolicyARNSelector selects a reference to an Policy
                      to retrieve its Policy ARN
                    properties:
                      matchControllerRef:
                        description: MatchControllerRef ensures an object with the
                          same controller reference as the selecting object is selected.
                        type: boolean
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: MatchLabels ensures an object with matching labels
                          is selected.
                        type: object
                    type: object
                  roleName:
                    description: RoleName presents the name of the IAM role.
                    type: string
                  roleNameRef:
                    description: RoleNameRef references an Role to retrieve its Name
                    properties:
                      name:
                        description: Name of the referenced object.
                        type: string
                    required:
                    - name
                    type: object
                  roleNameSelector:
                    description: RoleNameSelector selects a reference to an Role to
                      retrieve its Name
                    properties:
                      matchControllerRef:
                        description: MatchControllerRef ensures an object with the
                          same controller reference as the selecting object is selected.
                        type: boolean
                      matchLabels:
                        additionalProperties:
                          type: string
                        description: MatchLabels ensures an object with matching labels
                          is selected.
                        type: object
                    type: object