apiVersion: cdn.xplane.dfds.cloud/v1alpha1
kind: AWSDistributionV1alpha1
metadata:
  name: awsdistributiondfds
  namespace: my-namespace
spec:
  parameters:
    region: us-east-1
    distributionConfig:
      enabled: false # set to false before deleting the claim
      comment: Example CloudFront Distribution S3 origin
      origins:
        items:
          - domainName: crossplane-example-bucket.s3.amazonaws.com
            id: s3Origin
            s3OriginConfig:
              originAccessIdentity: ""
      defaultCacheBehavior:
        targetOriginID: s3Origin
        viewerProtocolPolicy: allow-all
        minTTL: 0
        forwardedValues:
          cookies:
            forward: none
          queryString: false