apiVersion: crossplane.dfds.cloud/v1alpha1
kind: SqlDatabaseInstance
metadata:
  namespace: default
  name: dynamic-claim-example
spec:
  parameters:
    isProduction: false
    deletionPolicy: Orphan
  compositionSelector:
    matchLabels:
      provider: aws
  
  writeConnectionSecretToRef:
    name: dynamic-claim-example-secret