apiVersion: crossplane.dfds.cloud/v1alpha1
kind: SqlDatabaseInstance
metadata:
  namespace: default
  name: dynamic-claim-example
spec:
  parameters:
    isNonProduction: true
  compositionSelector:
    matchLabels:
      provider: aws
  
  writeConnectionSecretToRef:
    name: dynamic-claim-example-secret