apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xconfluenttopicaccessv1s.messaging.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xconfluenttopicaccessv1s.messaging.xplane.dfds.cloud
  group: messaging.xplane.dfds.cloud
  names:
    kind: XConfluentTopicAccessV1
    plural: xconfluenttopicaccessv1s
  claimNames:
    kind: ConfluentTopicAccessV1
    plural: confluenttopicaccessv1s
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                serviceaccountid:
                  type: string
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    deletionPolicy:
                      description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                      type: string
                      default: "Orphan"
                      enum:
                      - Delete
                      - Orphan
                    environment:
                      description: Provision topic in either prod or dev environment.
                      type: string
                      enum: ["prod", "dev"]
