apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawstopicv1s.messaging.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xawstopicv1s.messaging.xplane.dfds.cloud
  group: messaging.xplane.dfds.cloud
  names:
    kind: XAWSTopicV1
    plural: xawstopicv1s
  claimNames:
    kind: AWSTopicV1
    plural: awstopicv1s
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - name: Synced
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].status    
    - name: Last Change
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].lastTransitionTime     
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              createdResources:
                description: List of resources created for this claim
                type: object
                default: {}
                properties:
                  topic:
                    description: Name of the provisioned topic
                    type: string
                    default: ""
                  rbac:
                    description: List of the provisioned RBAC resources
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    default: {}
              instanceConditions:
                description: >
                  Information about the managed resource condition, e.g. reconcile errors due to bad parameters
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true                    
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  deletionPolicy: 
                    description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                    type: string
                    default: "Delete"               
                  deliveryPolicy:
                    description: DeliveryRetryPolicy - the JSON serialization of the
                      effective delivery policy, taking system defaults into account
                    type: string
                  displayName:
                    description: The display name to use for a topic with SNS subscriptions.
                    type: string
                  kmsMasterKeyId:
                    description: "Setting this enables server side encryption at-rest
                      to your topic. The ID of an AWS-managed customer master key
                      (CMK) for Amazon SNS or a custom CMK \n For more examples, see
                      KeyId (https://docs.aws.amazon.com/kms/latest/APIReference/API_DescribeKey.html#API_DescribeKey_RequestParameters)
                      in the AWS Key Management Service API Reference."
                    type: string
                  name:
                    description: Name refers to the name of the AWS SNS Topic
                    type: string
                  policy:
                    description: The policy that defines who can access your topic.
                      By default, only the topic owner can publish or subscribe to
                      the topic.
                    type: string
                  region:
                    description: Region is the region you'd like your Topic to be
                      created in.
                    type: string
                  tags:
                    description: Tags represetnt a list of user-provided metadata
                      that can be associated with a SNS Topic. For more information
                      about tagging, see Tagging SNS Topics (https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html)
                      in the SNS User Guide.
                    items:
                      description: Tag represent a user-provided metadata that can
                        be associated with a SNS Topic. For more information about
                        tagging, see Tagging SNS Topics (https://docs.aws.amazon.com/sns/latest/dg/sns-tags.html)
                        in the SNS User Guide.
                      properties:
                        key:
                          description: The key name that can be used to look up or
                            retrieve the associated value. For example, Department
                            or Cost Center are common choices.
                          type: string
                        value:
                          description: "The value associated with this tag. For example,
                            tags with a key name of Department could have values such
                            as Human Resources, Accounting, and Support. Tags with
                            a key name of Cost Center might have values that consist
                            of the number associated with the different cost centers
                            in your company. Typically, many resources have tags with
                            the same key name but with different values. \n AWS always
                            interprets the tag Value as a single string. If you need
                            to store an array, you can store comma-separated values
                            in the string. However, you must interpret the value in
                            your code."
                          type: string
                      required:
                      - key
                      type: object
                    type: array
                required:
                - name
                - region