# Example configmaps that are required for providing needed configurations for the Confluent compositions
apiVersion: v1
kind: ConfigMap
metadata:
  name: confluent-cluster-id
  namespace: upbound-system
data:
  dev: cluster-dev-example
  prod: cluster-prod-example
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: confluent-environment-id
  namespace: upbound-system
data:
  dev: env-dev-example
  prod: env-prod-example
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: confluent-clusters-endpoints
  namespace: upbound-system
data:
  dev: cluster-endpoint1
  prod: cluster-endpoint2