# Example configmaps that are required for providing needed configurations for the Confluent compositions
apiVersion: v1
kind: ConfigMap
metadata:
  name: clusterid
  namespace: upbound-system
data:
  dev: cluster-dev-example
  prod: cluster-prod-example
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: environmentid
  namespace: upbound-system
data:
  dev: env-dev-example
  prod: env-prod-example