apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsqueuev1s.messaging.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xawsqueuev1s.messaging.xplane.dfds.cloud
  group: messaging.xplane.dfds.cloud
  names:
    kind: XAWSQueueV1
    plural: xawsqueuev1s
  claimNames:
    kind: AWSQueueV1
    plural: awsqueuev1s
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - name: Synced
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].status    
    - name: Last Change
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].lastTransitionTime    
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              createdResources:
                description: List of resources created for this claim
                type: object
                properties:
                  sqs:
                    description: Name of the provisioned SQS queue
                    type: string
                  rbac:
                    description: List of the provisioned RBAC resources
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              instanceConditions:
                description: >
                  Freeform field containing information about the instance condition, e.g. reconcile errors due to bad parameters
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true                    
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  deletionPolicy: 
                    description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                    type: string
                    default: "Delete"                
                  contentBasedDeduplication:
                    description: 'ContentBasedDeduplication - Enables content-based
                      deduplication. Valid values: true, false. For more information,
                      see Exactly-Once Processing (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-exactly-once-processing)
                      in the Amazon Simple Queue Service Developer Guide. Every message
                      must have a unique MessageDeduplicationId, You may provide a
                      MessageDeduplicationId explicitly. If you aren''t able to provide
                      a MessageDeduplicationId and you enable ContentBasedDeduplication
                      for your queue, Amazon SQS uses a SHA-256 hash to generate the
                      MessageDeduplicationId using the body of the message (but not
                      the attributes of the message). If you don''t provide a MessageDeduplicationId
                      and the queue doesn''t have ContentBasedDeduplication set, the
                      action fails with an error. If the queue has ContentBasedDeduplication
                      set, your MessageDeduplicationId overrides the generated one.
                      When ContentBasedDeduplication is in effect, messages with identical
                      content sent within the deduplication interval are treated as
                      duplicates and only one copy of the message is delivered. If
                      you send one message with ContentBasedDeduplication enabled
                      and then another message with a MessageDeduplicationId that
                      is the same as the one generated for the first MessageDeduplicationId,
                      the two messages are treated as duplicates and only one copy
                      of the message is delivered.'
                    type: boolean
                  delaySeconds:
                    description: 'DelaySeconds - The length of time, in seconds, for
                      which the delivery of all messages in the queue is delayed.
                      Valid values: An integer from 0 to 900 (15 minutes). Default:
                      0.'
                    format: int64
                    type: integer
                  fifoQueue:
                    description: "FIFOQueue - Designates a queue as FIFO. Valid values:
                      true, false. If \tyou don't specify the FifoQueue attribute,
                      Amazon SQS creates a standard \tqueue. You can provide this
                      attribute only during queue creation. You \tcan't change it
                      for an existing queue. When you set this attribute, you \tmust
                      also provide the MessageGroupId for your messages explicitly.
                      For \tmore information, see FIFO Queue Logic (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html#FIFO-queues-understanding-logic)
                      \tin the Amazon Simple Queue Service Developer Guide."
                    type: boolean
                  kmsDataKeyReusePeriodSeconds:
                    description: 'KMSDataKeyReusePeriodSeconds - The length of time,
                      in seconds, for which Amazon SQS can reuse a data key (https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#data-keys)
                      to encrypt or decrypt messages before calling AWS KMS again.
                      An integer representing seconds, between 60 seconds (1 minute)
                      and 86,400 seconds (24 hours). Default: 300 (5 minutes). A shorter
                      time period provides better security but results in more calls
                      to KMS which might incur charges after Free Tier. For more information,
                      see How Does the Data Key Reuse Period Work? (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html#sqs-how-does-the-data-key-reuse-period-work).
                      Applies only to server-side-encryption (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html):'
                    format: int64
                    type: integer
                  kmsMasterKeyId:
                    description: 'KMSMasterKeyID - The ID of an AWS-managed customer
                      master key (CMK) for Amazon SQS or a custom CMK. For more information,
                      see Key Terms (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html#sqs-sse-key-terms).
                      While the alias of the AWS-managed CMK for Amazon SQS is always
                      alias/aws/sqs, the alias of a custom CMK can, for example, be
                      alias/MyAlias . For more examples, see KeyId (https://docs.aws.amazon.com/kms/latest/APIReference/API_DescribeKey.html#API_DescribeKey_RequestParameters)
                      in the AWS Key Management Service API Reference. Applies only
                      to server-side-encryption (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html):'
                    type: string
                  maximumMessageSize:
                    description: 'MaximumMessageSize is the limit of how many bytes
                      a message can contain before Amazon SQS rejects it. Valid values:
                      An integer from 1,024 bytes (1 KiB) up to 262,144 bytes (256
                      KiB). Default: 262,144 (256 KiB).'
                    format: int64
                    type: integer
                  messageRetentionPeriod:
                    description: 'MessageRetentionPeriod - The length of time, in
                      seconds, for which Amazon SQS retains a message. Valid values:
                      An integer representing seconds, from 60 (1 minute) to 1,209,600
                      (14 days). Default: 345,600 (4 days).'
                    format: int64
                    type: integer
                  policy:
                    description: The queue's policy. A valid AWS policy. For more
                      information about policy structure, see Overview of AWS IAM
                      Policies (https://docs.aws.amazon.com/IAM/latest/UserGuide/PoliciesOverview.html)
                      in the Amazon IAM User Guide.
                    type: string
                  receiveMessageWaitTimeSeconds:
                    description: 'ReceiveMessageWaitTimeSeconds - The length of time,
                      in seconds, for which a ReceiveMessage action waits for a message
                      to arrive. Valid values: an integer from 0 to 20 (seconds).
                      Default: 0.'
                    format: int64
                    type: integer
                  redrivePolicy:
                    description: RedrivePolicy includes the parameters for the dead-letter
                      queue functionality of the source queue. For more information
                      about the redrive policy and dead-letter queues, see Using Amazon
                      SQS Dead-Letter Queues (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html)
                      in the Amazon Simple Queue Service Developer Guide
                    properties:
                      deadLetterTargetArn:
                        description: The Amazon Resource Name (ARN) of the dead-letter
                          queue to which Amazon SQS moves messages after the value
                          of maxReceiveCount is exceeded.
                        type: string
                      deadLetterTargetArnRef:
                        description: DeadLetterTargetARNRef reference a Queue to retrieve
                          its ARN.
                        properties:
                          name:
                            description: Name of the referenced object.
                            type: string
                        required:
                        - name
                        type: object
                      deadLetterTargetArnSelector:
                        description: DeadLetterTargetARNSelector selects reference
                          to a Queue to retrieve its ARN
                        properties:
                          matchControllerRef:
                            description: MatchControllerRef ensures an object with
                              the same controller reference as the selecting object
                              is selected.
                            type: boolean
                          matchLabels:
                            additionalProperties:
                              type: string
                            description: MatchLabels ensures an object with matching
                              labels is selected.
                            type: object
                        type: object
                      maxReceiveCount:
                        description: The number of times a message is delivered to
                          the source queue before being moved to the dead-letter queue.
                        format: int64
                        type: integer
                    required:
                    - maxReceiveCount
                    type: object
                  region:
                    description: Region is the region you'd like your Queue to be
                      created in.
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    description: Tags add cost allocation tags to the specified Amazon
                      SQS queue.
                    type: object
                  visibilityTimeout:
                    description: 'VisibilityTimeout - The visibility timeout for the
                      queue, in seconds. Valid values: an integer from 0 to 43,200
                      (12 hours). Default: 30. For more information about the visibility
                      timeout, see Visibility Timeout (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html)
                      in the Amazon Simple Queue Service Developer Guide.'
                    format: int64
                    type: integer
                required:
                - region
            required:
            - parameters
