apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmyresource.resourcegroup.crossplane.dfds.cloud
spec:
  compositeTypeRef:
    apiVersion: resourceapigroup/groupapiversion
    kind: XMyResource
  patchSets:
  - name: configname
    patches:
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-vendor"
      policy:
        fromFieldPath: Required
  resources:
  - name: rbac
    base:
      apiVersion: crossplane.dfds.cloud/v1alpha1
      kind: XRBAC
      spec:
        resourceTypes:
        - iamroles
        apiGroups:
        - identity.aws.crossplane.io
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.resourceName
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.resourceNamespace
    - type: ToCompositeFieldPath
      fromFieldPath: status.createdResources
      toFieldPath: status.createdResources.rbac
      policy:
        fromFieldPath: Optional
  
  - name: myadditionalresource
