apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsrolepolicyattachments.identity.crossplane.dfds.cloud
spec:
  compositeTypeRef:
    apiVersion: identity.crossplane.dfds.cloud/v1alpha1
    kind: XAWSRolePolicyAttachment

  patchSets:
  - name: configname
    patches:
    - fromFieldPath: spec.claimRef.namespace    
      toFieldPath: spec.providerConfigRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-aws"
      policy:
        fromFieldPath: Required    
  
  resources:
  - name: rbac
    base:
      apiVersion: crossplane.dfds.cloud/v1alpha1
      kind: XRBAC
      spec:
        resourceTypes:
        - rolepolicyattachments
        apiGroups:
        - iam.aws.crossplane.io
        providerConfigRef:
          name: kubernetes-provider
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: spec.resourceName
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.resourceNamespace
    - type: ToCompositeFieldPath
      fromFieldPath: status.createdResources
      toFieldPath: status.createdResources.rbac
      policy:
        fromFieldPath: Optional
                  
  - name: RolePolicyAttachment
    base:
      apiVersion: iam.aws.crossplane.io/v1beta1
      kind: RolePolicyAttachment
    patches:
    - type: PatchSet
      patchSetName: configname
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name          
    - fromFieldPath: spec.parameters
      toFieldPath: spec.forProvider
    - type: FromCompositeFieldPath
      fromFieldPath: "metadata.annotations[crossplane.io/external-name]"
    - fromFieldPath: spec.parameters.deletionPolicy
      toFieldPath: spec.deletionPolicy
    - type: ToCompositeFieldPath
      fromFieldPath: "metadata.name"
      toFieldPath: "status.createdResources.rolepolicyattachement"           
      toFieldPath: "status.createdResources.iamrolepolicyattachement"
    - type: ToCompositeFieldPath
      fromFieldPath: status.conditions
      toFieldPath: status.instanceConditions
      policy:
        fromFieldPath: Optional
