apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcontainerregistryv1s.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xcontainerregistryv1s.xplane.dfds.cloud
  group: xplane.dfds.cloud
  names:
    kind: XContainerRegistryV1
    plural: xcontainerregistryv1s
  claimNames:
    kind: ContainerRegistryV1
    plural: containerregistryv1s
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - name: Synced
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].status
    - name: Last Change
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].lastTransitionTime
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              createdResources:
                description: List of resources created for this claim
                type: object
                default: {}
                properties:
                  repository:
                    description: Name of the provisioned repository
                    type: string
                    default: ""
                  repositorypolicy:
                    description: Name of the provisioned repositorypolicy
                    type: string
                    default: ""
                  rbac:
                    description: List of the provisioned RBAC resources
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
                    default: {}
              instanceConditions:
                description: >
                  Information about the managed resource condition, e.g. reconcile errors due to bad parameters
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              exportedAttributes:
                description: >
                  Properties exported from the provider about the managed resource.
                type: object
                default: {}
                properties:
                  repositoryUri:
                    description: Container repo URI
                    type: string
                    default: ""
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  name:
                    description: repo name
                    type: string
                  deletionPolicy:
                    description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                    type: string
                    default: "Delete"
                    enum: ["Delete", "Orphan"]
                  enableSecurityScanOnPush:
                    description: Enable image security scan on push.
                    type: boolean
                    default: true
                  mutability:
                    description: Allow for mutable tags, i.e. tags can be overwritten.
                    type: string
                    enum: ["MUTABLE", "IMMUTABLE"]
                    default: "IMMUTABLE"
                  region:
                    description: Geographic location of resources.
                    type: string
                    enum: ["ireland", "germany"]
                    default: "ireland"
                required:
                - name