apiVersion: storage.crossplane.dfds.cloud/v1alpha1
kind: AWSBucket
metadata: 
  name: s3testsamdiv11
  namespace: default
spec:
  parameters:
    locationConstraint: eu-west-1
    acl: public-read
  compositionSelector:
    matchLabels:
      provider: aws