apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsrolev1s.identity.xplane.dfds.cloud
spec:
  defaultCompositionRef:
    name: xawsrolev1s.identity.xplane.dfds.cloud
  group: identity.xplane.dfds.cloud
  names:
    kind: XAWSRoleV1
    plural: xawsrolev1s
  claimNames:
    kind: AWSRoleV1
    plural: awsrolev1s
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    additionalPrinterColumns:
    - name: Synced
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].status    
    - name: Last Change
      type: string
      jsonPath: .status.instanceConditions[?(@.type=='Synced')].lastTransitionTime     
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              createdResources:
                description: list of resources created for this claim
                type: object
                properties:
                  role:
                    description: Name of the provisioned IAM role
                    type: string
                  rbac:
                    description: list of the provisioned RBAC resources
                    type: object
                    x-kubernetes-preserve-unknown-fields: true
              instanceConditions:
                description: >
                  Information about the managed resource condition, e.g. reconcile errors due to bad parameters
                type: array
                items:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true                    
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  deletionPolicy: 
                    description: Specify whether the actual cloud resource should be deleted when this managed resource is deleted in Kubernetes API server. Possible values are Delete (the default) and Orphan
                    type: string
                    default: "Delete"               
                  assumeRolePolicyDocument:
                    description: AssumeRolePolicyDocument is the the trust relationship
                      policy document that grants an entity permission to assume the
                      role.
                    type: string
                  description:
                    description: Description is a description of the role.
                    type: string
                  maxSessionDuration:
                    description: 'MaxSessionDuration is the duration (in seconds)
                      that you want to set for the specified role. The default maximum
                      of one hour is applied. This setting can have a value from 1
                      hour to 12 hours. Default: 3600'
                    format: int32
                    type: integer
                  path:
                    description: 'Path is the path to the role. Default: /'
                    type: string
                  permissionsBoundary:
                    description: PermissionsBoundary is the ARN of the policy that
                      is used to set the permissions boundary for the role.
                    type: string
                  tags:
                    description: Tags. For more information about tagging, see Tagging
                      IAM Identities (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html)
                      in the IAM User Guide.
                    items:
                      description: Tag represents user-provided metadata that can
                        be associated with a IAM role. For more information about
                        tagging, see Tagging IAM Identities (https://docs.aws.amazon.com/IAM/latest/UserGuide/id_tags.html)
                        in the IAM User Guide.
                      properties:
                        key:
                          description: The key name that can be used to look up or
                            retrieve the associated value. For example, Department
                            or Cost Center are common choices.
                          type: string
                        value:
                          description: "The value associated with this tag. For example,
                            tags with a key name of Department could have values such
                            as Human Resources, Accounting, and Support. Tags with
                            a key name of Cost Center might have values that consist
                            of the number associated with the different cost centers
                            in your company. Typically, many resources have tags with
                            the same key name but with different values. \n AWS always
                            interprets the tag Value as a single string. If you need
                            to store an array, you can store comma-separated values
                            in the string. However, you must interpret the value in
                            your code."
                          type: string
                      required:
                      - key
                      type: object
                    type: array
                required:
                - assumeRolePolicyDocument
